* 前書き
** Lispについて

Lispは元々は計算モデルの記述法として誕生し、後に実装されプログラミングに使えることが分かったという特異な出自を持つ言語だ。その歴史は古く、最初にそのアイディアが提唱されてから60年以上が経とうとしている。それにも関わらず、様々がLisp方言が現在でも様々なプラットフォーム上で使われ続けている。
その理由としては、Lispの基本原理が非常にコンパクトであり実装が容易であること、そして言語の拡張が容易なのでその時々の最新の言語機能を実験したり、アプリケーション組込みの言語として使えたということが挙げられる。

Lisp方言のうち、現在でも実際のプロダクトの開発に活用されているものの代表がClojureとCommon Lispである。ClojureはJVM言語であり、Javaの既存のライブラリ群との相互運用が可能で、幅広いプラットフォーム上で動作するという特徴がある。Common LispはANSI(米国規格協会)で言語仕様が定められており、ANSI規格に従って書かれたプログラムには可搬性があり、将来に渡って動くことが保証される。そのような理由から、Common Lispは産業や軍事、AI研究などの分野で利用されてきた。
本書の執筆陣は電子マネープラットフォームを開発しているポケットチェンジ社のメンバーが中心となっているが、ここでも決済システムやWebバックエンドにCommon Lispが利用されている。

** 本書の目的と対象読者

本書はCommon Lispの最近の開発フローやツールの解説、及び具体的なプロジェクト例で構成される。Common Lispの言語解説書は質、量ともにそれなりに出揃っている感があるが、その一方でどのように環境を構築し、プロジェクトを作っていけばいいのかという具体的な指針に欠けていた。本書はその部分をカバーすることを目的としており、言語そのものの解説は主目的ではない。
そのため対象読者は、Common Lispに興味があり、言語仕様などは調べたが(あるいは調べられるが)、具体的にどのようにプロジェクトを開発していけばいいのか分からないという人、これからCommon Lispの世界に入っていこうとする人になる。また、既にCommon Lispを使って開発をしているが、最近のツールについて知りたいという人も対象になるだろう。

** 既存のCommon Lispの本

前述した通り、本書ではCommon Lispの文法自体の説明はしないので、おすすめの言語解説書をいくつか挙げておく。本書と併わせて活用してもらいたい。

実践Common Lisp: 本格的な言語解説書。実例も多く最初の一冊に適している。原書は無料公開されている。
実用Common Lisp: 通称PAIP。古典的なAI開発を通じてCommon Lispを学ぶ。原書は無料公開されている。
Land of Lisp: テキストベースのゲーム開発を通じてCommon Lispを学ぶ。
On Lisp: Common Lispのマクロを中心に解説した本。事例も豊富。原書は無料公開されている。

** 各章の概要と執筆者について

*** 1. Roswell
*** 2. Lem
*** 3. ライブラリの調査方法、コミュニティ
*** 4. プロジェクトの作り方
*** 5. プロジェクト例1: Webスクレイピング
*** 6. プロジェクト例2: チャットボット
*** 7. テスト
*** 8. ライブラリの配布方法
*** 9. デプロイ
